### ISSUE TITLE
Unexpected token `??=`

### ISSUE THREAD

**Issue by ml20221206** [livekit-examples/meet#129]
![image](https://github.com/livekit-examples/meet/assets/120362079/7cf0ae93-109f-4c9f-89c0-9ed765d925f2)

dev:~/tools/livekit-examples/meet# yarn dev

...

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at Module.mod.require (/root/tools/livekit-examples/meet/node_modules/next/dist/server/require-hook.js:64:28)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/root/tools/livekit-examples/meet/node_modules/next/dist/telemetry/post-payload.js:17:19)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:6483) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6483) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.15s.

I need your help, thank you very much!

**Comment by Ocupe** [comment]
Hi @ml20221206. It seems that your browser/node.js version does not support the Nullish Coalescing Assignment `??=`.  Can you share what bowser/node.js version you are on? Is it possible to update to a browser/node version that supports the nullish coalescing assignment [Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_assignment#browser_compatibility)?

**Comment by lukasIO** [comment]
for reference, meet issue is solved by https://github.com/livekit-examples/meet/pull/151
