### ISSUE TITLE
Warning: useLayoutEffect does nothing on the server

### ISSUE THREAD

**Issue by ile** [livekit-examples/meet#93]
I'm getting this error when running the latest versions of LiveKit & livekit-examples / meet (on a local dev machine using VM installation), and doing a hard refresh in the browser at url `/rooms/10u9-pu2s`:

```
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at MediaDeviceMenu (file:///home/ile/src/sc2/aamu-meet-web/node_modules/@livekit/components-react/dist/index.mjs:2512:5)
    at div
    at div
    at div
    at div
    at PreJoin (file:///home/ile/src/sc2/aamu-meet-web/node_modules/@livekit/components-react/dist/index.mjs:2729:5)
    at div
    at main
    at Home (webpack-internal:///./pages/rooms/[name].tsx:29:74)
    at MyApp (webpack-internal:///./pages/_app.tsx:20:18)
    at StyleRegistry (/home/ile/src/sc2/aamu-meet-web/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/home/ile/src/sc2/aamu-meet-web/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/home/ile/src/sc2/aamu-meet-web/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/home/ile/src/sc2/aamu-meet-web/node_modules/next/dist/server/render.js:614:21)
Warning: useLayoutEffect does nothing on the server, because its effect cannot be encoded into the server renderer's output format. This will lead to a mismatch between the initial, non-hydrated UI and the intended UI. To avoid this, useLayoutEffect should only be used in components that render exclusively on the client. See https://reactjs.org/link/uselayouteffect-ssr for common fixes.
    at MediaDeviceMenu (file:///home/ile/src/sc2/aamu-meet-web/node_modules/@livekit/components-react/dist/index.mjs:2512:5)
    at div
    at div
    at div
    at div
    at PreJoin (file:///home/ile/src/sc2/aamu-meet-web/node_modules/@livekit/components-react/dist/index.mjs:2729:5)
    at div
    at main
    at Home (webpack-internal:///./pages/rooms/[name].tsx:29:74)
    at MyApp (webpack-internal:///./pages/_app.tsx:20:18)
    at StyleRegistry (/home/ile/src/sc2/aamu-meet-web/node_modules/styled-jsx/dist/index/index.js:448:36)
    at AppContainer (/home/ile/src/sc2/aamu-meet-web/node_modules/next/dist/server/render.js:298:29)
    at AppContainerWithIsomorphicFiberStructure (/home/ile/src/sc2/aamu-meet-web/node_modules/next/dist/server/render.js:327:57)
    at div
    at Body (/home/ile/src/sc2/aamu-meet-web/node_modules/next/dist/server/render.js:614:21)

```

**Comment by lukasIO** [comment]
That's unexpected, this should have been fixed recently with https://github.com/livekit/components-js/pull/553. 
Running `yarn install && yarn dev` on main within this repo also doesn't give me those warnings. Are you sure you are using the latest components version?

**Comment by ile** [comment]
I don't seem to get it anymore - did `rm -rf yarn.lock node_modules && yarn install`. Thanks!
